### ISSUE TITLE
fn id() -> TypeId<T> should be const

### ISSUE THREAD

**Issue by Bajix** [vityafx/unique-type-id#67]
[unique_type_id::UniqueTypeId::id](https://docs.rs/unique-type-id/1.0.0/unique_type_id/trait.UniqueTypeId.html#tymethod.id) should be made const because doing so can allow other optimizations outside this crate. For my use case, this would be used to create unique redis key prefixes as static bytes.

**Comment by iddm** [comment]
Hi @Bajix, and thank you for your contribution. Let me do it so.

**Comment by iddm** [comment]
Actually, this is a function of a trait, and those can't be made `const` as those have to be a part of the trait object (vtable). I think I can just provide an `impl` for the target type without the trait, let's see.

**Comment by iddm** [comment]
Here it is: https://github.com/vityafx/unique-type-id/commit/da95909da22aea5e3fac3d84ab2b687639581a24
https://crates.io/crates/unique-type-id-derive/1.2.0
https://crates.io/crates/unique-type-id/1.2.0

An example can be seen in the tests:
```rust
#[test]
fn check_simple_second() {
    use unique_type_id::UniqueTypeId;
    #[derive(UniqueTypeId)]
    struct Test1;
    #[derive(UniqueTypeId)]
    struct Test2;
    #[derive(UniqueTypeId)]
    struct Test3;
    #[derive(UniqueTypeId)]
    struct Test4;
    #[derive(UniqueTypeId)]
    struct Test5;

    assert_eq!(Test1::id().0, 1u64);
    assert_eq!(Test2::id().0, 2u64);
    assert_eq!(Test3::id().0, 5u64);
    assert_eq!(Test4::id().0, 0u64);
    assert_eq!(Test5::id().0, 3u64);

    assert_eq!(Test1::unique_type_id().0, 1u64);
    assert_eq!(Test2::unique_type_id().0, 2u64);
    assert_eq!(Test3::unique_type_id().0, 5u64);
    assert_eq!(Test4::unique_type_id().0, 0u64);
    assert_eq!(Test5::unique_type_id().0, 3u64);
}
```
That said, it provides an implementation:
```rust
impl Test1 {
    const fn unique_type_id() -> unique_type_id::TypeId<#id_type> {
        Self::TYPE_ID
    }
}
```

However, I think this is redundant since we also have access to the associated constant:
```rust
    assert_eq!(Test1::TYPE_ID, Test1::id());
    assert_eq!(Test2::TYPE_ID, Test2::id());
    assert_eq!(Test3::TYPE_ID, Test3::id());
    assert_eq!(Test4::TYPE_ID, Test4::id());
    assert_eq!(Test5::TYPE_ID, Test5::id());
```
So, probably, I will re-think this and remove the function actually.

**Comment by Bajix** [comment]
Thanks!
